[package]
name = "magnet-rs"
version = "0.1.0"
authors = ["Peter Dunne <peter.dunne@applied-magnetism.com>"]
edition = "2018"
description = "User friendly magnetic field calculations in Rust"
homepage = "https://github.com/pdunne/"
repository = "https://github.com/pdunne/magnet-rs"
readme = "README.md"
keywords =["magnetism", "magnetic", "field", "calculations", ]
categories = ["mathematics", "science", "simulation"]
license = "MPL-2.0"


# [lib]
# name = "magnet-rs"
# crate-type = ["cdylib"]

# [dependencies.pyo3]
# version = "0.13.1"
# features = ["extension-module"]


[dependencies]
# num-traits = "0.2"

[package.metadata.docs.rs]
rustdoc-args = [
    "--html-in-header",
    "./src/katex.html"
] 


